#!/bin/bash -ev
set -o pipefail
echo makeforwardport starting command: makeforwardport $1 $2 $3 $4 $5
PACKAGE=$1 
OLDVERSION=$2
DEBVERSION=$3
NEWVERSION=$4
TARGETSUITE=$5

NEWVERSIONNOEPOCH=`echo ${NEWVERSION} | sed -e s/^[^:]://`
OLDVERSIONNOEPOCH=`echo ${OLDVERSION} | sed -e s/^[^:]://`
DEBVERSIONNOEPOCH=`echo ${DEBVERSION} | sed -e s/^[^:]://`


if [[ $PACKAGE == lib* ]]; then
    PACKAGEDIR=${PACKAGE:0:4}/$PACKAGE
else
    PACKAGEDIR=${PACKAGE:0:1}/$PACKAGE
fi

DEBDIFF=/build/debdiffs/*/$PACKAGEDIR/${PACKAGE}_${OLDVERSIONNOEPOCH}.debdiff

cd /build/tmp/
(filterdiff -p1 -i debian/changelog $DEBDIFF | grep -v ^+++ | grep ^+ | cut -c 2- > debdiffchangelogentries) || (echo changelog extraction failed, is the debdiff sane? && false)
filterdiff -p1 -i debian/patches/series $DEBDIFF > debdiffseries
filterdiff -p1 -x debian/changelog -x debian/patches/series $DEBDIFF > debdiffwithoutchangelogorseries

rm -rf extract
dpkg-source -x  --skip-patches /build/workingrepo/pool/*/$PACKAGEDIR/${PACKAGE}_${DEBVERSIONNOEPOCH}.dsc extract

preparechangelogentry debdiffchangelogentries $NEWVERSION $TARGETSUITE "`date -uR`" $PACKAGE > processedchangelogentry
OUTPUTDEBDIFF=/build/autoforwardporter/output/${PACKAGE}_${NEWVERSIONNOEPOCH}_generated.debdiff
echo '--- a/debian/changelog' > $OUTPUTDEBDIFF
echo '+++ b/debian/changelog' >> $OUTPUTDEBDIFF
echo '@@ -0,0 +0,'`wc -l processedchangelogentry | cut -d ' ' -f 1 `' @@' >> $OUTPUTDEBDIFF
sed -e s/^/+/ processedchangelogentry >> $OUTPUTDEBDIFF
processseriesdiff debdiffseries extract/debian/patches/series >> $OUTPUTDEBDIFF
cat debdiffwithoutchangelogorseries >> $OUTPUTDEBDIFF

cd extract
patch -p1 --no-backup-if-mismatch  < $OUTPUTDEBDIFF

#defuzz patches
export QUILT_PATCHES=debian/patches
quilt push -a --fuzz 0 || true
while quilt push; do
	quilt refresh
	quilt push -a --fuzz 0 || true
done

cd /build/autoforwardporter/output/
dcmd --orig cp /build/workingrepo/pool/*/$PACKAGEDIR/${PACKAGE}_${DEBVERSIONNOEPOCH}.dsc .
dpkg-source -b /build/tmp/extract
#going forward it would be good to have more inteligent application of --force-orig-source, not a massive priority for now though
sbuild -snA --force-orig-source -d ${TARGETSUITE} ${PACKAGE}_${NEWVERSIONNOEPOCH}.dsc
